### ISSUE TITLE
Add an “icon” room attribute

### ISSUE THREAD

**Issue by heyitsmdr** [armeria-dev/armeria#23]
This room attribute will be used for displaying an icon over the room on the minimap.

As part of this issue, we will need to figure out which icons / icon sets we want to use for this and set that up on the client-side as well.

Once the attribute is added, we will need to pass it to the client when sending minimap data so the client can render it.

The values of this attribute should be locked down to the icons that we actually support. This field shouldn’t support an arbitrary value.

**Comment by joshschmille** [comment]
What types of icons did you have in mind here? Some example ideas would help figure out an icon set to find/create.

**Comment by heyitsmdr** [comment]
I'm thinking icons for things along the lines of:

- Shops (perhaps different icons for different types of shops)
- Taverns
- Player House Entrances
- Train Station Entrances
- Banks
- Markets (Auction house / global exchange type of thing)

**Comment by joshschmille** [comment]
I was playing around with https://www.flaticon.com/ and put together a small collection that included icons for the items listed.

You can download the collection as an icon font.

I had to modify some of the CSS for the minimap to get it to display properly, but other than that, it worked great.

What do you think of just using an icon font that we put together this way? We would have to add them to the attribution list if we use them for free, but that shouldn't be a problem.

In the screenshot below, I have set it to automatically add a bed icon to any track rooms.
![Screenshot from 2019-08-16 09-43-51](https://user-images.githubusercontent.com/3855149/63176018-c17e5a00-c00a-11e9-80cd-33d37c48f65b.png)

The bank icon has the follow CSS changes:
* Room div -
`opacity: 1;`
`text-align: center;`
and to make it match closer to the other tracks, just for visual reference, I modified the background/border colors to be more transparent.

* Icon element -
`vertical-align: middle;`

**Comment by heyitsmdr** [comment]
I think those look good! An icon font would be perfectly fine IMO. I have no problem with adding them to the attribution list, which I should probably go ahead and start one somewhere.
