### ISSUE TITLE
Create a YAML config file for the server

### ISSUE THREAD

**Issue by heyitsmdr** [armeria-dev/armeria#26]
Instead of passing in command-line arguments for all of the config, we should switch over to reading from a `config.yaml` file. The location of this file can be configurable via the command-line argument `-c <path>`.

The production yaml should be separated from the development yaml. If the `-c` command-line argument is not passed, it should default to the development yaml.

**Comment by Mohannad-Zeido** [comment]
Hello,

Based on what i have seen, this change will be done in the `init` function where it gets passed in the path to the config file and it gets the config from there. 
Am I on the right track? I would like to work on this.

**Comment by heyitsmdr** [comment]
That would be awesome if you could work on this! Be sure to assign yourself to this issue if you'd like to tackle it.

Yeah, that's along the lines of what I was thinking. You could either use the `init` function, or even just place it in the `main` function, since it will only ever be ran once.

You'd use the [flag](https://golang.org/pkg/flag/) package and accept a `-c` (or `-config`) to pass in the path to the config file that the server will use. The default value for this should be a valid config for local development, which we can place within `/configs/development.yml`. There will be another `/configs/production.yml` which will be used for the game running in production.

For loading the config, I imagine there would be a `config.go` which would contain a `Config` struct with yaml identifiers. You would unmarshal the config and have it loaded into the struct. This should be made available in `state.go` so it can be accessed from anywhere within the `armeria` package.

**Comment by Mohannad-Zeido** [comment]
I have created a pull request with the changes completed.

**Comment by heyitsmdr** [comment]
Thanks! It has been merged :)
