### ISSUE TITLE
Implementing help command

### ISSUE THREAD

**Issue by Mohannad-Zeido** [armeria-dev/armeria#34]
Hey,

I would like to add a help command which displays the help statement for each of the commands. Would that be ok?

**Comment by joshschmille** [comment]
Currently, you can use /commands within the client to see a list of all commands available to you, as well as a brief description of each one in the list.

The current plan is to use /help to provide players with more gameplay related assistance.

Thanks for taking the time to check out the project!

**Comment by Mohannad-Zeido** [comment]
Fair enough
