### ISSUE TITLE
Modifying a room should automatically refresh the minimap

### ISSUE THREAD

**Issue by joshschmille** [armeria-dev/armeria#42]
Currently, you have to manually do /refresh.

This will be useful when changing the room's color or type. It will also be useful when connecting a room to another area, once that is implemented.

**Comment by heyitsmdr** [comment]
When doing a `/room set`, we can always render the minimap for safe measures. This can be done by calling `ctx.Player.client.RenderMap()`. Tagging this issue as a good first issue.

**Comment by joshschmille** [comment]
Resolved in #51
