### ISSUE TITLE
Revamp Minimap using PixiJS

### ISSUE THREAD

**Issue by heyitsmdr** [armeria-dev/armeria#65]
The current minimap is based on using many HTML `div`'s (creating a div for every room within an area) and simply moves the container `div` to represent movement. To better support larger areas, improved graphics and transitional states (ie: going between areas), we can switch over to rendering this on a Canvas using a 2D rendering engine -- PixiJS.

**Comment by joshschmille** [comment]
Done: https://github.com/heyitsmdr/armeria/pull/66
