### ISSUE TITLE
Wrap long descriptions by a configurable amount

### ISSUE THREAD

**Issue by heyitsmdr** [armeria-dev/armeria#92]
Using something like [muesli/reflow](https://github.com/muesli/reflow), we should wrap long descriptions so they don't go the full width of the text area. This can be a configurable setting in `/settings`.

**Comment by joshschmille** [comment]
I think by default, everything should wrap at 80. I know we are stepping away from the old, and there's no technical reason for 80 being the number here, but it's familiar to anyone who has played a mud

**Comment by heyitsmdr** [comment]
Yeah, that's what I was thinking as well. Either 80 or 100, both are pretty familiar defaults.

**Comment by heyitsmdr** [comment]
This was done in 412c1e5.
